# _____  _____
# | __\ \/ / _ \
# | _| >  <|  _/
# |___/_/\_\_|_ _  _____ ___ ___ _    ___ ___ ___
# |  \/  | | | | ||_   _|_ _| _ \ |  |_ _| __| _ \
# | |\/| | |_| | |__| |  | ||  _/ |__ | || _||   /
# |_|  |_|\___/|____|_| |___|_| |____|___|___|_|_\
#
# ExpMultiplier - Developed by Ladinn
# https://github.com/torreyleonard/ExpMultiplier
#
# Main configuration
#
# Default experience multiplier on server load. (default: 1)
defaultMultiplier: 1
#
# Display action bar message when experience multiplier is set. Requires ActionBarAPI. (default: true)
showActionBar: true
